=head1 NAME

makepkg-meta - create and install custom meta-packages

=head1 SYNOPSIS

 makepkg-meta [options]

=head1 OPTIONS

=over

=item B<-n>, B<--name>=I<pkgname>

Specify the package name.

=item B<-u>, B<--update>=I<pkgname>

Equivalent to B<--name> except if a package named I<pkgname> is currently
installed it will be queried for any fields not explicitly provided.

=item B<--description>=I<pkgdesc>

Specify the package description.

=item B<--depends>=I<dependency>

Comma-separated list of package dependencies.  May be specified multiple times.

=item B<-a>, B<--add-depends>=I<dependency>

Comma-separated list of package dependencies.  Dependencies are added to the
depends list I<after> loading existing dependencies.  May be specified multiple
times.

=item B<-r>, B<--rm-depends>=I<dependency>

Comma-separates list of dependencies to be removed from the depends list
I<after> loading existing dependencies.  May be specified multiple times.

=item B<--groups>=I<group>

Comma-separated list of package groups.  May be specified multiple times.
Packages are automatically in the C<meta> group.

=item B<--add-groups>=I<group>

Comma-separated list of package groups.  Groups are added to the group list
I<after> loading existing groups.  May be specified multiple times.

=item B<--rm-groups>=I<groups>

Comma-separates list of groups to be removed from the group list I<after>
loading existing groups.  May be specified multiple times.

=item B<--dump>

Write the resulting PKGBUILD to F<stdout> without building or installing it.

=item B<--help>

Display brief help information.

=item B<--version>

Display version information.

=back

=head1 EXAMPLES

Create and install a new meta-package:

 makepkg-meta -n foo --description 'foo meta package' -a bar,baz

Update an installed meta-package with explicit dependencies.

 makepkg-meta -u foo --depends qux

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2013 Andrew Gregory L<andrew.gregory.8@gmail.com>

makepkg-meta is provided under the terms of the MIT license.  See F<COPYING>
for details.
